language: ruby
sudo: false
cache: bundler

bundler_args: --without local_development

script: bundle exec rake

rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby
  - jruby-9.0.5.0
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
    - rvm: rbx-2
  fast_finish: true
